name: Coptit Bot CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v2
      with:
        node-version: "19.x"
    - run: npm ci
    - run: npm run format
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Format code"
        branch: ${{ github.head_ref }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "kunalsin9h" --password-stdin
        docker image build -t kunalsin9h/coptit-bot:latest .
        docker push kunalsin9h/coptit-bot:latest
